const Map<String, String> ar = {
  "language": "إنجليزي",
  "appNameText": "فاخر منفرد",
  "aboutUsText": "معلومات عنا",
  "referFriendText": "ادع صديق",
  "returnsRefundsText": "العوائد والمردودات",
  "faqText": "التعليمات",
  "contactText": "اتصل",
  "socialText": "اجتماعي",
  "companyText": "شركة",
  "contactUs": "اتصل بنا",
  "myOrders": "طلباتي",
  "myOrderImage": "صورة",
  "productName": "اسم المنتج",
  "sku": "SKU",
  "price": "السعر",
  "quantity": "الكمية",
  "status": "حالة",
  "action": "عمل",
  "paymentMethod": " طريقة الدفع او السداد",
  "shippingAddress": "عنوان الشحن",
  "billingAddress": "عنوان وصول الفواتير",
  "continueShopping": "مواصلة التسوق",
  "freuentlyAskedQueText": "أسئلة مكررة",
  "shopAndPlaceOrder": "كيف تتسوق وتضع طلب؟",
  "accountToPlaceOrderQues": "هل أحتاج إلى حساب لتقديم طلب؟",
  "accountToPlaceOrderAns":
      "لا ، كل ما تحتاجه هو عنوان بريد إلكتروني. نوصيك بالتسجيل للحصول على حساب لبدء إضافة قطع إلى قائمة الرغبات الخاصة بك ، ولكن يمكنك أيضًا تقديم الطلبات وتتبعها كضيف والاشتراك في الوقت الذي يناسبك.",
  "registeredCustomersText": "العملاء المسجلين",
  "registeredCustomersDescriptionText": "إذا كان لديك حساب ، قم بتسجيل الدخول باستخدام \ n عنوان بريدك الإلكتروني.",
  "usernameText": "اسم المستخدم",
  "passwordText": "كلمة المرور",
  "signInText": "تسجيل الدخول",
  "forgotYourPasswordText": "نسيت رقمك السري؟",
  "newCustomersText": "زبائن الجدد",
  "loginDescriptionText":
      "إنشاء حساب له فوائد عديدة: تحقق \ n بشكل أسرع ، واحتفظ بأكثر من عنوان واحد \ n تتبع الطلبات والمزيد.",
  "createAccountText": "إنشاء حساب",
  "firstNameText": "الاسم الأول",
  "lastNameText": "الكنية",
  "dateOfBirthText": "تاريخ الميلاد",
  "pleaseSelectValidDateText": "الرجاء تحديد تاريخ صالح",
  "marriageAnniversaryText": "ذكرى الزواج",
  "emailText": "بريد الالكتروني",
  "confirmPasswordText": "تأكيد كلمة المرور",
  "signUpForNewsletterText": "الاشتراك في النشرة الإخبارية",
  "forgotYourPasswordDescriptionText":
      "الرجاء إدخال عنوان بريدك الإلكتروني أدناه لتلقي \ n ارتباط إعادة تعيين كلمة المرور",
  "enterYourEmailText": "أدخل بريدك الإلكتروني",
  "resetMyPasswordText": "إعادة تعيين كلمة المرور الخاصة بي",
  "accessYourAccountDetailsText": "الوصول إلى تفاصيل حسابك والمكافآت",
  "signUpText": "اشتراك",
  "myOrdersText": "طلباتي",
  "myWishlistText": "قائمة امنياتي",
  "addressBookText": "دليل العناوين",
  "accountInformationText": "معلومات الحساب",
  "myTicketsText": "تذاكري",
  "trackOrderText": "ترتيب المسار",
  "companyMyAccountText": "شركة",
  "contactUsText": "اتصل بنا",
  "secureShoppingText": "تسوق آمن",
  "advancedSearchText": "البحث المتقدم",
  "testimonialsText": "الشهادات - التوصيات",
  "socialMyAccountText": "اجتماعي",
  "hopeText": "آمل أن",
  "affiliateProgramText": "إنضم لبرنامج",
  "influencerRegistrationText": "تسجيل المؤثر",
  "exchangeText": "التبادل والإرجاع",
  "contactMyAccountText": "جهات الاتصال",
  "privacyPolicyText": "سياسة خاصة",
  "termsConditionsText": "البنود و الظروف",
  "shippingText": "شحن",
  "aboutText": "حول",
  "aboutUsMyAccountText": "معلومات عنا",
  "referFriendMyAccountText": "ادع صديق",
  "returnsText": "العوائد والمردودات",
  "faqMyAccountText": "التعليمات",
  "myAccountText": "حسابي",
  "filtersText": "المرشحات",
  "priceText": "السعر",
  "colorText": "اللون",
  "brandText": "ماركة",
  "sizeText": "بحجم",
  "applyText": "تطبيق",
  "searchText": "بحث..",
  "aboutUsContain1": "SOLO هي أفضل وجهة للأزياء الفاخرة عبر الإنترنت مع 5 ملايين زائر شهريًا وشحن عالمي.",
  "aboutUsContain2":
      'Tيتميز موقعه الإلكتروني بأفضل اختيار لأفضل المصممين بالإضافة إلى المواهب الناشئة الشابة. تأسست Solo في فلورنسا في أوائل ثلاثينيات القرن الماضي ، مع افتتاح متجر مفهوم مسمى للشركة في Via Roma.Online منذ عام 1999 ، تنسب الشركة 90٪ من إجمالي الإيرادات إلى المبيعات عبر الإنترنت. حتى يومنا هذا ، لا تزال شركة عائلية مملوكة للقطاع الخاص بنسبة 100٪ ، حيث يتولى حفيد المؤسس ، أندريا بانكونيسي ، منصب الرئيس التنفيذي وابنته ، أناغريتا بانكونيزي ، مديرة إبداعية.',
  "aboutUsContain3":
      'Tيقدم الموقع مجموعة واسعة من الملابس والأحذية والحقائب والإكسسوارات والديكورات المنزلية الفاخرة والجمال ، مع منتجات متاحة للرجال والنساء والأطفال من أشهر المصممين مثل Balenciaga و Vetements و Off-White و J.W. Anderson و Balmain و Dolce & Gabbana و Gucci و Saint Laurent و Valentino و Givenchy و Loewe و Jacquemus والمزيد.',
  "aboutUsContain4":
      'يوجد حاليًا 200 شخص من 15 دولة مختلفة يعملون على إنتاج Solo وصيانته. الموقع متاح بـ 9 لغات: الإنجليزية والإيطالية والألمانية والصينية والروسية والإسبانية والفرنسية والكورية واليابانية. تم إنشاء الموقع داخليًا بالكامل ، من خلال مكتب فلورنسا للتصميم الجرافيكي وتكنولوجيا المعلومات وخدمة العملاء والتسويق والشراء. يعمل المصممون والفرق الصحفية من مكتب Solo في عاصمة الموضة في العالم - ميلان.',
  "aboutUsContain5":
      'يتم شحن جميع الطلبات في جميع أنحاء العالم من المقر الرئيسي لشركة Solo في صناديق يتم إعدادها بأقصى قدر من العناية وتستخدم أفضل المواد ، من أكياس الأحذية المميزة إلى الشريط المخصص.',
  "aboutUsContain6":
      'كان لدى سولو 1.5 مليون زائر فريد يصلون إلى الموقع في عام 2008 ونما إلى 53 مليون زائر فريد في عام 2017. ويتم إنشاء أكثر من 15٪ من المبيعات عبر الإنترنت من الولايات المتحدة ، تليها ألمانيا والمملكة المتحدة وإيطاليا والصين وفرنسا.',
  "aboutUsContain7":
      'يدفع Solo حدود مشهد البيع بالتجزئة الفاخرة سواء عبر الإنترنت أو بدونه من خلال مجموعة من الخدمات الحصرية ومبادرات العلامات التجارية بما في ذلك Buy It First و Luxury Club و Sneakers Club و LVR Privilege و LVR Editions.',
  "profile": "Pملف",
  "ContactNoText": "رقم الاتصال.",
  "websiteUrlText": "رابط الموقع",
  "countryText": "دولة",
  "postCodeText": "الرمز البريدي",
  "socialLinksText": "روابط اجتماعية",
  "facebookText": "فيسبوك",
  "instagramText": "إنستغرام",
  "twitterText": "تويتر",
  "youtubeText": "موقع يوتيوب",
  "linkendinText": "لينكيندين",
  "pinterestText": "بينتيريست",
  "followersText": "متابعون",
  "workedOnText": "عملت المشاريع",
  "mr": "السيد.",
  "yourEmail1Text": "بريدك الالكتروني",
  "subscribeText": "الإشتراك",
  "menuText": "قائمة",
  "accountText": "حساب",
  "checkOutText": "الدفع",
  "purchaseText": "الرجاء إدخال التفاصيل الخاصة بك أدناه لإكمال عملية الشراء",
  "shippingAddressText": "عنوان الشحن",
  "shippingMethodText": "طريقة الشحن",
  "paymentMethodText": "طريقة الدفع او السداد",
  "orderSummaryText": "ملخص الطلب",
  "alreadyAcText": "لديك بالفعل حساب معنا. تسجيل الدخول أو الاستمرار كضيف.",
  "loginText": "تسجيل الدخول",
  "forgotText": "نسيت رقمك السري؟",
  "stLineText": "العنوان (الخط 1",
  "cityText": "مدينة",
  "japanText": "اليابان",
  "stateText": "الولاية / المقاطعة",
  "zipPostalText": "الرمز البريدي / الرمز البريدي",
  "phoneNumberText": "رقم التليفون",
  "itemInCartText": "عنصر في عربة التسوق",
  "qtyText": "الكمية",
  "viewDetailsText": "عرض التفاصيل",
  "applyDisCodeText": "تطبيق كود الخصم",
  "enterDisCodeText": "أدخل رمز الخصم",
  "applyDiscountText": "تطبيق الخصم",
  "orderTotalText": "الطلب الكلي",
  "placeOrderText": "مكان الامر",
  "homeText": "الصفحة الرئيسية",
  "search1Text": "بحث",
  "designersText": "المصممون",
  "wishListText": "قائمة الرغبات",
  "storePaymentText": "طرق الدفع المخزنة",
  "newsLetterText": "اشتراك الرسائل الإخبارية",
};
