const Map<String, String> en = {
  "language": "English",
  "appNameText": "Solo Luxury",
  "aboutUsText": "About us",
  "referFriendText": "Refer Friend",
  "returnsRefundsText": "Returns & Refunds",
  "faqText": "FAQ",
  "contactText": "Contact",
  "socialText": "Social",
  "companyText": "Company",
  "chooseYourCountryText": "Choose your country",
  "addressText": "Address",
  "billingText": "Default\nBilling",
  "shippingText": "Default\nShipping",
};
