const Map<String, String> en = {
  "language": "English",
  "appNameText": "Solo Luxury",
  "aboutUsText": "About us",
  "referFriendText": "Refer Friend",
  "returnsRefundsText": "Returns & Refunds",
  "faqText": "FAQ",
  "contactText": "Contact",
  "socialText": "Social",
  "companyText": "Company",
  "chooseYourCountryText": "Choose your country",
  "addressText": "Address",
  "billingText": "Default\nBilling",
  "shippingText": "Default\nShipping",
  "yourAppExpericanceText": "Your app experience is set to",
  "indiaText": "INDIA (IND) - ENGLISH (IND)",
  "englishIsAlsoText":
      "ENGLISH is also available in your\nlocation. Would you like to change?",
  "noThanksText": "No, Thanks",
  "changeText": "CHANGE",
  "myAccountText": "My Account",
  "myOrdersText": "My Orders",
  "myWidhListText": "My Wish List",
  "addressBookText": "Address Book",
  "accountInfoText": "Account Information",
  "storePaymentText": "Store Payment Methods",
  "newsletterSubText": "Newsletter Subscriptions",
};
