const Map<String, String> en = {
  "language": "English",
  "appNameText": "Solo Luxury",
  "aboutUsText": "About us",
  "aboutUsContain1":
      "SOLO IS A TOP ONLINE LUXURYFASHION DESTINATION WITH 5 MILLION VISITORS PER MONTHAND WORLDWIDE SHIPPING.",
  "aboutUsContain2":
      'The website features the best selection of thetop established designers as wellas young emerging talents. Solo was founded in Florence in the early 1930s, with the opening of the company’s eponymous concept store on Via Roma.Online since 1999, the company attributes 90% of total revenue to online sales. To this day it remains a 100% privately owned family business, with the founder’s grandson, Andrea Panconesi acting as CEO and his daughter, Annagreta Panconesi as Creative Director.',
  "aboutUsContain3":
      'The site offers a wide selection of clothing, shoes, bags, accessories, luxuryhome interiors and beauty, with products available for men, women and kids from the most prestigious designers such as Balenciaga, Vetements, Off-White,J.W. Anderson, Balmain, Dolce & Gabbana, Gucci, Saint Laurent, Valentino, Givenchy, Loewe, Jacquemus and more.',
  "aboutUsContain4":
      'There are currently 200 people from 15 different countries that work to produce and maintain Solo. The site is available in 9 languages: English, Italian, German, Chinese, Russian, Spanish, French,Korean and Japanese. The site is created entirely in-house, with the Florence office housing graphic design, IT,customer service, marketing and buying departments. The stylists and press teams operate from the Solo office in the fashion capital of the world – Milan.',
  "aboutUsContain5":
      'All orders are shipped worldwide from the Solo headquarters in boxes that are prepared with maximum care and use the finest materials, from the signature shoe bags to the personalized ribbon.',
  "aboutUsContain6":
      'Solo had 1.5 million unique visitors access the site in 2008 and has grown to 53 million unique visitors in 2017. More than 15% of online sales are generated from the United States, followed by Germany, UK, Italy, China and France.',
  "aboutUsContain7":
      'Solo pushes the boundaries of the luxury retail landscape both on and offline with an array of exclusive services and trademark initiatives including Buy It First, Luxury Club, Sneakers Club, LVR Privilege and LVR Editions.',
  "referFriendText": "Refer Friend",
  "profile": "Profile",
  "firstNameText": "First Name",
  "lastNameText": "Last Name",
  "emailText": "Email",
  "ContactNoText": "Contact no.",
  "websiteUrlText": "Website URL",
  "cityText": "City",
  "countryText": "Country",
  "postCodeText": "Post Code",
  "socialLinksText": "Social links",
  "facebookText": "Facebook",
  "instagramText": "Instagram",
  "twitterText": "Twitter",
  "youtubeText": "Youtube",
  "linkendinText": "Linkendin",
  "pinterestText": "Pinterest",
  "followersText": "Followers",
  "workedOnText": "Projects worked on",
  "mr": "Mr.",
  "returnsRefundsText": "Returns & Refunds",
  "faqText": "FAQ",
  "contactText": "Contact",
  "socialText": "Social",
  "companyText": "Company",
  "myOrdersText": "My Orders",
  "myWishlistText": "My Wish List",
  "addressBookText": "Address Book",
  "accountInformationText": "Account Information",
  "myTicketsText": "My Tickets",
  "myAccountText": "My Account",
  "newsLetters": "NEWSLETTERS",
  "manageAddresses": "Manage Addresses",
  "defaultBillingAddress": "DEFAULT BILLING ADDRESS",
  "defaultShippingAddress": "DEFAULT SHIPPING ADDRESS",
  "defaultShippingContain": "sdsdsd sdsdsd sds ds sdsd kl skldjlsdjklsdjljsl jaipur, Delhi, 302019 India",
  "newsLettersContain": "You Aren't Subscribed To\nOur Newsletter.",
  "edit": "EDIT",
  "editAddress": "EDIT ADDRESS",
};
