const Map<String, String> es = {
  "language": "inglés",
  "appNameText": "Solo de lujo",
  "aboutUsText": "Sobre nosotros",
  "referFriendText": "Recomendar amigo",
  "returnsRefundsText": "Devoluciones y reembolsos",
  "faqText": "Preguntas más frecuentes",
  "contactText": "Contacto",
  "socialText": "Social",
  "companyText": "Compañía",
  "contactUs": "Contáctenos",
  "myOrders": "Mis ordenes",
  "myOrderImage": "Imagen",
  "productName": "nombre del producto",
  "sku": "SKU",
  "price": "Precio",
  "quantity": "Cantidad",
  "status": "Estado",
  "action": "Acción",
  "paymentMethod": " Método de pago",
  "shippingAddress": "Dirección de envío",
  "billingAddress": "Dirección de Envio",
  "continueShopping": "Seguir comprando",
  "freuentlyAskedQueText": "Preguntas frecuentes",
  "shopAndPlaceOrder": "¿Cómo comprar y hacer un pedido?",
  "accountToPlaceOrderQues": "¿Necesito una cuenta para hacer un pedido?",
  "accountToPlaceOrderAns": "No, todo lo que necesita es una dirección de correo electrónico. Le recomendamos que se registre para obtener una cuenta para comenzar a agregar piezas a su Lista de deseos, pero también puede realizar y realizar un seguimiento de los pedidos como invitado y registrarse en el momento que más le convenga.",
  "registeredCustomersText": "Clientes Registrados",
  "registeredCustomersDescriptionText": "Si tiene una cuenta, inicie sesión con su\ndirección de correo electrónico.",
  "usernameText": "Nombre de usuario",
  "passwordText": "Clave",
  "signInText": "Registrarse",
  "forgotYourPasswordText": "¿Olvidaste tu contraseña?",
  "newCustomersText": "nuevos clientes",
  "loginDescriptionText": "Crear una cuenta tiene muchos beneficios: pagar\nmás rápido, mantener más de una dirección\nseguir pedidos y más.",
  "createAccountText": "Crear una cuenta",
  "firstNameText": "Primer nombre",
  "lastNameText": "Apellido",
  "dateOfBirthText": "Fecha de nacimiento",
  "pleaseSelectValidDateText": "Seleccione una fecha válida",
  "marriageAnniversaryText": "Aniversario de boda",
  "emailText": "Correo electrónico",
  "confirmPasswordText": "Confirmar contraseña",
  "signUpForNewsletterText": "Regístrese para recibir el boletín",
  "forgotYourPasswordDescriptionText": "Ingrese su dirección de correo electrónico a continuación para recibir\nUn enlace de restablecimiento de contraseña",
  "enterYourEmailText": "Introduce tu correo electrónico",
  "resetMyPasswordText": "Restablecer mi contraseña",
  "accessYourAccountDetailsText": "Acceda a los detalles de su cuenta y recompensas",
  "signUpText": "INSCRIBIRSE",
  "myOrdersText": "Mis ordenes",
  "myWishlistText": "Mi lista de deseos",
  "addressBookText": "Directorio",
  "accountInformationText": "Información de la cuenta",
  "myTicketsText": "Mis entradas",
  "trackOrderText": "Orden de pista",
  "companyMyAccountText": "Compañía",
  "contactUsText": "Contáctenos",
  "secureShoppingText": "Compras seguras",
  "advancedSearchText": "Búsqueda Avanzada",
  "testimonialsText": "Testimonios",
  "socialMyAccountText": "Social",
  "hopeText": "Esperar",
  "affiliateProgramText": "programa de afiliación",
  "influencerRegistrationText": "Registro de influenciadores",
  "exchangeText": "Cambio y Devoluciones",
  "contactMyAccountText": "Contactos",
  "privacyPolicyText": "Política de privacidad",
  "termsConditionsText": "Términos y condiciones",
  "shippingText": "Transporte",
  "aboutText": "Sobre",
  "aboutUsMyAccountText": "Sobre nosotros",
  "referFriendMyAccountText": "Recomendar amigo",
  "returnsText": "Devoluciones y reembolsos",
  "faqMyAccountText": "Preguntas más frecuentes",
  "myAccountText": "Mi cuenta",
  "filtersText": "filtros",
  "priceText": "Precio",
  "colorText": "Color",
  "brandText": "Marca",
  "sizeText": "Tamaño",
  "applyText": "Aplicar",
  "searchText": "Búsqueda..",
  "aboutUsContain1": "SOLO ES UN PRINCIPAL DESTINO DE MODA DE LUJO EN LÍNEA CON 5 MILLONES DE VISITANTES AL MES Y ENVÍOS A TODO EL MUNDO.",
  "aboutUsContain2": "El sitio web presenta la mejor selección de los mejores diseñadores establecidos, así como jóvenes talentos emergentes. Solo se fundó en Florencia a principios de la década de 1930, con la apertura de la tienda conceptual homónima de la compañía en Via Roma. En línea desde 1999, la compañía atribuye el 90% de los ingresos totales a las ventas en línea. A día de hoy sigue siendo una empresa familiar 100% privada, con el nieto del fundador, Andrea Panconesi, como director general y su hija, Annagreta Panconesi, como directora creativa.",
  "aboutUsContain3": "El sitio ofrece una amplia selección de ropa, zapatos, bolsos, accesorios, interiores de casas de lujo y belleza, con productos disponibles para hombres, mujeres y niños de los diseñadores más prestigiosos como Balenciaga, Vetements, Off-White, J.W. Anderson, Balmain, Dolce & Gabbana, Gucci, Saint Laurent, Valentino, Givenchy, Loewe, Jacquemus y más.",
  "aboutUsContain4": 'Actualmente hay 200 personas de 15 países diferentes que trabajan para producir y mantener Solo. El sitio está disponible en 9 idiomas: inglés, italiano, alemán, chino, ruso, español, francés, coreano y japonés. El sitio se crea completamente internamente, con la oficina de Florencia que alberga los departamentos de diseño gráfico, TI, servicio al cliente, marketing y compras. Los estilistas y los equipos de prensa operan desde la oficina de Solo en la capital mundial de la moda: Milán.',
  "aboutUsContain5": 'Todos los pedidos se envían a todo el mundo desde la sede de Solo en cajas que se preparan con el máximo cuidado y utilizan los mejores materiales, desde las exclusivas bolsas para zapatos hasta la cinta personalizada.',
  "aboutUsContain6": 'Solo tuvo 1,5 millones de visitantes únicos que accedieron al sitio en 2008 y creció a 53 millones de visitantes únicos en 2017. Más del 15 % de las ventas en línea se generan en los Estados Unidos, seguido de Alemania, el Reino Unido, Italia, China y Francia.',
  "aboutUsContain7": 'Solo supera los límites del panorama minorista de lujo tanto en línea como fuera de línea con una variedad de servicios exclusivos e iniciativas de marcas registradas que incluyen Buy It First, Luxury Club, Sneakers Club, LVR Privilege y LVR Editions.',
  "profile": "Perfil",
  "ContactNoText" : "Nro. de contacto",
  "websiteUrlText" : "URL del sitio web",
  "countryText" : "País",
  "postCodeText" : "Código postal",
  "socialLinksText" : "Vínculos sociales",
  "facebookText" : "Facebook",
  "instagramText" : "Instagram",
  "twitterText" : "Gorjeo",
  "youtubeText" : "YouTube",
  "linkendinText" : "Linkendín",
  "pinterestText" : "Pinterés",
  "followersText" : "Seguidores",
  "workedOnText" : "Proyectos trabajados",
  "mr": "Señor.",
  "yourEmail1Text": "Tu correo electrónico",
  "subscribeText": "SUSCRIBIR",
  "menuText": "Menú",
  "accountText": "Cuenta",
  "checkOutText": "Verificar",
  "purchaseText": "Ingrese sus datos a continuación para completar su compra",
  "shippingAddressText": "Dirección de envío",
  "shippingMethodText": "Método de envío",
  "paymentMethodText": "Método de pago",
  "orderSummaryText": "Resumen del pedido",
  "alreadyAcText": "Ya tienes una cuenta con nosotros. Regístrese o continúe como invitado.",
  "loginText": "ACCESO",
  "forgotText": "¿Olvidaste tu contraseña?",
  "stLineText": "Dirección (Línea 1",
  "cityText": "Ciudad",
  "japanText": "Japón",
  "stateText": "Provincia del estado",
  "zipPostalText": "Código postal",
  "phoneNumberText": "Número de teléfono",
  "itemInCartText": "artículo en carrito",
  "qtyText": "Cantidad",
  "viewDetailsText": "Ver detalles",
  "applyDisCodeText": "Aplicar código de descuento",
  "enterDisCodeText": "Introduzca el código de descuento",
  "applyDiscountText": "Aplicar descuento",
  "orderTotalText": "Total del pedido",
  "placeOrderText": "REALIZAR PEDIDO",
};
