const Map<String, String> fr = {
  "language": "Anglais",
  "appNameText": "Luxe en solitaire",
  "aboutUsText": "À propos de nous",
  "referFriendText": "Référez un ami",
  "returnsRefundsText": "Retours et remboursements",
  "faqText": "FAQ",
  "contactText": "Contact",
  "socialText": "Social",
  "companyText": "Compagnie",
  "contactUs": "Nous contacter",
  "myOrders": "Mes commandes",
  "myOrderImage": "Image",
  "productName": "Nom du produit",
  "sku": "UGS",
  "price": "Prix",
  "quantity": "Qté",
  "status": "Statut",
  "action": "action",
  "paymentMethod": " Mode de paiement",
  "shippingAddress": "Adresse de livraison",
  "billingAddress": "Adresse de facturation",
  "continueShopping": "Continuer vos achats",
  "freuentlyAskedQueText": "Questions fréquemment posées",
  "shopAndPlaceOrder": "Comment magasiner et passer une commande?",
  "accountToPlaceOrderQues": "Ai-je besoin d'un compte pour passer une commande?",
  "accountToPlaceOrderAns": "Non, tout ce dont vous avez besoin est une adresse e-mail. Nous vous recommandons de créer un compte pour commencer à ajouter des pièces à votre liste de souhaits, mais vous pouvez également passer et suivre des commandes en tant qu'invité et vous inscrire au moment qui vous convient.",
  "registeredCustomersText": "Clients enregistrés",
  "registeredCustomersDescriptionText": "Si vous avez un compte, connectez-vous avec votre\nadresse e-mail.",
  "usernameText": "Nom d'utilisateur",
  "passwordText": "Mot de passe",
  "signInText": "S'identifier",
  "forgotYourPasswordText": "Mot de passe oublié?",
  "newCustomersText": "nouveaux clients",
  "loginDescriptionText": "La création d'un compte présente de nombreux avantages : paiement\nplus rapide, conservation de plusieurs adresses\nsuivi des commandes, etc.",
  "createAccountText": "Créer un compte",
  "firstNameText": "Prénom",
  "lastNameText": "Nom de famille",
  "dateOfBirthText": "Date de naissance",
  "pleaseSelectValidDateText": "Veuillez sélectionner une date valide",
  "marriageAnniversaryText": "Anniversaire de mariage",
  "emailText": "E-mail",
  "confirmPasswordText": "Confirmez le mot de passe",
  "signUpForNewsletterText": "S'inscrire aux Newsletters",
  "forgotYourPasswordDescriptionText": "Veuillez saisir votre adresse e-mail ci-dessous pour recevoir\nun lien de réinitialisation du mot de passe",
  "enterYourEmailText": "Entrer votre Email",
  "resetMyPasswordText": "Réinitialiser mon mot de passe",
  "accessYourAccountDetailsText": "Accéder aux détails de votre compte et aux récompenses",
  "signUpText": "S'INSCRIRE",
  "myOrdersText": "Mes commandes",
  "myWishlistText": "Ma liste d'envies",
  "addressBookText": "Carnet d'adresses",
  "accountInformationText": "Information sur le compte",
  "myTicketsText": "Mes billets",
  "trackOrderText": "Suivi de commande",
  "companyMyAccountText": "Compagnie",
  "contactUsText": "Nous contacter",
  "secureShoppingText": "Achats sécurisés",
  "advancedSearchText": "Recherche Avancée",
  "testimonialsText": "Témoignages",
  "socialMyAccountText": "Social",
  "hopeText": "Espérer",
  "affiliateProgramText": "Programme d'affiliation",
  "influencerRegistrationText": "Inscription des influenceurs",
  "exchangeText": "Échange et retours",
  "contactMyAccountText": "Contacts",
  "privacyPolicyText": "Politique de confidentialité",
  "termsConditionsText": "termes et conditions",
  "shippingText": "Expédition",
  "aboutText": "Sur",
  "aboutUsMyAccountText": "À propos de nous",
  "referFriendMyAccountText": "Référez un ami",
  "returnsText": "Retours et remboursements",
  "faqMyAccountText": "FAQ",
  "myAccountText": "Mon compte",
  "filtersText": "Filtres",
  "priceText": "Prix",
  "colorText": "Couleur",
  "brandText": "Marque",
  "sizeText": "Taille",
  "applyText": "Appliquer",
  "searchText": "Rechercher..",
  "aboutUsContain1": "SOLO EST UNE DESTINATION DE MODE DE LUXE EN LIGNE AVEC 5 MILLIONS DE VISITEURS PAR MOIS ET UNE EXPÉDITION DANS LE MONDE ENTIER.",
  "aboutUsContain2": "Le site Web présente la meilleure sélection des meilleurs designers établis ainsi que de jeunes talents émergents. Solo a été fondée à Florence au début des années 1930, avec l'ouverture du concept store éponyme de l'entreprise sur la Via Roma. En ligne depuis 1999, l'entreprise attribue 90 % de son chiffre d'affaires total aux ventes en ligne. À ce jour, elle reste une entreprise familiale 100 % privée, avec le petit-fils du fondateur, Andrea Panconesi, en tant que PDG et sa fille, Annagreta Panconesi, en tant que directrice de la création.",
  "aboutUsContain3": "Le site propose une large sélection de vêtements, chaussures, sacs, accessoires, intérieurs de luxe et beauté, avec des produits disponibles pour hommes, femmes et enfants des créateurs les plus prestigieux tels que Balenciaga, Vetements, Off-White, J.W. Anderson, Balmain, Dolce & Gabbana, Gucci, Saint Laurent, Valentino, Givenchy, Loewe, Jacquemus et plus encore.",
  "aboutUsContain4": 'Il y a actuellement 200 personnes de 15 pays différents qui travaillent pour produire et maintenir Solo. Le site est disponible en 9 langues : anglais, italien, allemand, chinois, russe, espagnol, français, coréen et japonais. Le site est entièrement créé en interne, avec les bureaux de Florence abritant les départements de conception graphique, informatique, service client, marketing et achats. Les stylistes et les équipes de presse opèrent depuis le bureau de Solo dans la capitale mondiale de la mode - Milan.',
  "aboutUsContain5": 'Toutes les commandes sont expédiées dans le monde entier depuis le siège social de Solo dans des boîtes préparées avec le plus grand soin et utilisant les meilleurs matériaux, des sacs à chaussures emblématiques au ruban personnalisé.',
  "aboutUsContain6": '''Solo comptait 1,5 million de visiteurs uniques sur le site en 2008 et est passé à 53 millions de visiteurs uniques en 2017. Plus de 15 % des ventes en ligne sont générées aux États-Unis, suivis de l'Allemagne, du Royaume-Uni, de l'Italie, de la Chine et de la France.''',
  "aboutUsContain7": '''Solo repousse les limites du paysage de la vente au détail de luxe à la fois en ligne et hors ligne avec une gamme de services exclusifs et d'initiatives de marque, notamment Buy It First, Luxury Club, Sneakers Club, LVR Privilege et LVR Editions.''',
  "profile": "Profil",
  "ContactNoText" : "Numéro de contact.",
  "websiteUrlText" : "URL de site web",
  "countryText" : "De campagne",
  "postCodeText" : "Code postal",
  "socialLinksText" : "Liens sociaux",
  "facebookText" : "Facebook",
  "instagramText" : "Instagram",
  "twitterText" : "Twitter",
  "youtubeText" : "Youtube",
  "linkendinText" : "Linkendin",
  "pinterestText" : "Pinterest",
  "followersText" : "Suiveurs",
  "workedOnText" : "Les projets travaillés",
  "mr": "Monsieur.",
  "yourEmail1Text": "Votre e-mail",
  "subscribeText": "S'ABONNER",
  "menuText": "Menu",
  "accountText": "Compte",
  "checkOutText": "Vérifier",
  "purchaseText": "Veuillez entrer vos coordonnées ci-dessous pour finaliser votre achat",
  "shippingAddressText": "Adresse de livraison",
  "shippingMethodText": "Mode de livraison",
  "paymentMethodText": "Mode de paiement",
  "orderSummaryText": "Récapitulatif de la commande",
  "alreadyAcText": "Vous avez déjà un compte chez nous. Connectez-vous ou continuez en tant qu'invité.",
  "loginText": "CONNEXION",
  "forgotText": "Mot de passe oublié?",
  "stLineText": "Nom de rue (ligne 1",
  "cityText": "Ville",
  "japanText": "Japon",
  "stateText": "État/Province",
  "zipPostalText": "Zip / code postal",
  "phoneNumberText": "Numéro de téléphone",
  "itemInCartText": "Article dans le panier",
  "qtyText": "Qté",
  "viewDetailsText": "Voir les détails",
  "applyDisCodeText": "Appliquer le code de réduction",
  "enterDisCodeText": "Entrez le code de réduction",
  "applyDiscountText": "Appliquer la réduction",
  "orderTotalText": "Total de la commande",
  "placeOrderText": "PASSER LA COMMANDE",
  "storePaymentText": "MÉTHODES DE PAIEMENT MÉMORISÉES",
  "newsLetterText": "ABONNEMENT À LA NEWSLETTER",
};
