const Map<String, String> it = {
  "language": "inglese",
  "appNameText": "Lusso da solista",
  "aboutUsText": "Chi siamo",
  "referFriendText": "Segnala amico",
  "returnsRefundsText": "Resi e rimborsi",
  "faqText": "FAQ",
  "contactText": "Contatto",
  "socialText": "Sociale",
  "companyText": "Azienda",
  "contactUs": "Contattaci",
  "myOrders": "i miei ordini",
  "myOrderImage": "Immagine",
  "productName": "nome del prodotto",
  "sku": "SKU",
  "price": "Prezzo",
  "quantity": "Qtà",
  "status": "Stato",
  "action": "Azione",
  "paymentMethod": " Metodo di pagamento",
  "shippingAddress": "indirizzo di spedizione",
  "billingAddress": "Indirizzo Di Fatturazione",
  "continueShopping": "Continua a fare acquisti",
  "freuentlyAskedQueText": "Domande frequenti",
  "shopAndPlaceOrder": "Come acquistare e effettuare un ordine?",
  "accountToPlaceOrderQues": "Ho bisogno di un account per effettuare un ordine?",
  "accountToPlaceOrderAns": "No, tutto ciò che serve è un indirizzo email. Ti consigliamo di registrare un account per iniziare ad aggiungere pezzi alla tua lista dei desideri, ma puoi anche effettuare e monitorare gli ordini come ospite e iscriverti all'orario che preferisci.",
  "registeredCustomersText": "Clienti registrati",
  "registeredCustomersDescriptionText": "Se hai un account, accedi con il tuo\nindirizzo email.",
  "usernameText": "Nome utente",
  "passwordText": "Parola d'ordine",
  "signInText": "Registrazione",
  "forgotYourPasswordText": "Hai dimenticato la password?",
  "newCustomersText": "nuovi clienti",
  "loginDescriptionText": "La creazione di un account ha molti vantaggi: check\noout più veloce, mantenere più di un indirizzo\ntracciare gli ordini e altro ancora.",
  "createAccountText": "Creare un profilo",
  "firstNameText": "Nome di battesimo",
  "lastNameText": "Cognome",
  "dateOfBirthText": "Data di nascita",
  "pleaseSelectValidDateText": "Seleziona una data valida",
  "marriageAnniversaryText": "Anniversario di matrimonio",
  "emailText": "E-mail",
  "confirmPasswordText": "Conferma password",
  "signUpForNewsletterText": "Iscriviti alla Newsletter",
  "forgotYourPasswordDescriptionText": "Inserisci il tuo indirizzo e-mail qui sotto per ricevere\nun link per la reimpostazione della password",
  "enterYourEmailText": "Inserisci la tua email",
  "resetMyPasswordText": "Reimposta la mia password",
  "accessYourAccountDetailsText": "Accedi ai dettagli del tuo account e ai premi",
  "signUpText": "ISCRIZIONE",
  "myOrdersText": "i miei ordini",
  "myWishlistText": "La mia lista dei desideri",
  "addressBookText": "Rubrica",
  "accountInformationText": "Informazioni account",
  "myTicketsText": "I miei biglietti",
  "trackOrderText": "Ordine dei brani",
  "companyMyAccountText": "Azienda",
  "contactUsText": "Contattaci",
  "secureShoppingText": "Acquisti sicuri",
  "advancedSearchText": "Ricerca Avanzata",
  "testimonialsText": "Testimonianze",
  "socialMyAccountText": "Sociale",
  "hopeText": "Sperare",
  "affiliateProgramText": "programma affiliato",
  "influencerRegistrationText": "Registrazione influencer",
  "exchangeText": "Cambio e Resi",
  "contactMyAccountText": "Contatti",
  "privacyPolicyText": "politica sulla riservatezza",
  "termsConditionsText": "Termini & Condizioni",
  "shippingText": "Spedizione",
  "aboutText": "Di",
  "aboutUsMyAccountText": "Chi siamo",
  "referFriendMyAccountText": "Segnala amico",
  "returnsText": "Resi e rimborsi",
  "faqMyAccountText": "FAQ",
  "myAccountText": "Il mio conto",
  "filtersText": "Filtri",
  "priceText": "Prezzo",
  "colorText": "Colore",
  "brandText": "Marca",
  "sizeText": "Dimensione",
  "applyText": "Applicare",
  "searchText": "Ricerca..",
  "aboutUsContain1": "SOLO È UNA MIGLIORE DESTINAZIONE DELLA MODA DI LUSSO ONLINE CON 5 MILIONI DI VISITATORI AL MESE E SPEDIZIONI IN TUTTO IL MONDO.",
  "aboutUsContain2": "Il sito web presenta la migliore selezione dei migliori designer affermati e giovani talenti emergenti. Solo nasce a Firenze nei primi anni '30, con l'apertura dell'omonimo concept store in Via Roma.Online dal 1999, l'azienda attribuisce il 90% dei ricavi totali alle vendite online. Ad oggi rimane un'azienda familiare al 100% privata, con il nipote del fondatore, Andrea Panconesi in qualità di CEO e sua figlia, Annagreta Panconesi come Direttore Creativo.",
  "aboutUsContain3": "Il sito offre un'ampia selezione di abbigliamento, scarpe, borse, accessori, interni di lusso e bellezza, con prodotti disponibili per uomo, donna e bambino dei designer più prestigiosi come Balenciaga, Vetements, Off-White, J.W. Anderson, Balmain, Dolce & Gabbana, Gucci, Saint Laurent, Valentino, Givenchy, Loewe, Jacquemus e altri.",
  "aboutUsContain4": 'Attualmente ci sono 200 persone provenienti da 15 paesi diversi che lavorano per produrre e mantenere Solo. Il sito è disponibile in 9 lingue: inglese, italiano, tedesco, cinese, russo, spagnolo, francese, coreano e giapponese. Il sito è realizzato interamente in house, con la sede di Firenze che ospita gli uffici di progettazione grafica, informatica, servizio clienti, marketing e acquisti. Gli stilisti e i team stampa operano dalla sede di Solo nella capitale mondiale della moda – Milano.',
  "aboutUsContain5": 'Tutti gli ordini vengono spediti in tutto il mondo dalla sede di Solo in scatole preparate con la massima cura e utilizzando i migliori materiali, dalle esclusive borse per scarpe al nastro personalizzato.',
  "aboutUsContain6": 'Solo ha avuto 1,5 milioni di visitatori unici che accedono al sito nel 2008 ed è cresciuta fino a raggiungere i 53 milioni di visitatori unici nel 2017. Oltre il 15% delle vendite online è generato dagli Stati Uniti, seguiti da Germania, Regno Unito, Italia, Cina e Francia.',
  "aboutUsContain7": 'Solo spinge i confini del panorama della vendita al dettaglio di lusso sia online che offline con una serie di servizi esclusivi e iniziative di marchio tra cui Buy It First, Luxury Club, Sneakers Club, LVR Privilege e LVR Editions.',
  "profile": "Profilo",
  "ContactNoText" : "Contattare n.",
  "websiteUrlText" : "URL del sito",
  "countryText" : "Paese",
  "postCodeText" : "Codice postale",
  "socialLinksText" : "Collegamenti sociali",
  "facebookText" : "Facebook",
  "instagramText" : "Instagram",
  "twitterText" : "Twitter",
  "youtubeText" : "Youtube",
  "linkendinText" : "Linkendin",
  "pinterestText" : "Pinterest",
  "followersText" : "Seguaci",
  "workedOnText" : "Progetti lavorati",
  "mr": "Sig.",
  "yourEmail1Text": "La tua email",
  "subscribeText": "SOTTOSCRIVI",
  "menuText": "Menù",
  "accountText": "Account",
  "checkOutText": "Guardare",
  "purchaseText": "Inserisci i tuoi dettagli qui sotto per completare l'acquisto",
  "shippingAddressText": "indirizzo di spedizione",
  "shippingMethodText": "metodo di spedizione",
  "paymentMethodText": "Metodo di pagamento",
  "orderSummaryText": "Riepilogo ordine",
  "alreadyAcText": "Hai già un account con noi. Accedi o continua come ospite.",
  "loginText": "ACCEDERE",
  "forgotText": "Hai dimenticato la password?",
  "stLineText": "Indirizzo (linea 1",
  "cityText": "Città",
  "japanText": "Giappone",
  "stateText": "Stato/Provincia",
  "zipPostalText": "Zip / Codice postale",
  "phoneNumberText": "Numero di telefono",
  "itemInCartText": "Articolo nel carrello",
  "qtyText": "Qtà",
  "viewDetailsText": "Visualizza dettagli",
  "applyDisCodeText": "Applicare il codice sconto",
  "enterDisCodeText": "Inserisci il codice sconto",
  "applyDiscountText": "Applicare lo sconto",
  "orderTotalText": "Ordine totale",
  "placeOrderText": "INVIA ORDINE",
};
