const Map<String, String> ja = {
  "language": "英語",
  "appNameText": "ソロラグジュアリー",
  "aboutUsText": "私たちに関しては",
  "referFriendText": "友達を紹介する",
  "returnsRefundsText": "返品と返金",
  "faqText": "よくある質問",
  "contactText": "連絡先",
  "socialText": "社交",
  "companyText": "会社",
  "contactUs": "お問い合わせ",
  "myOrders": "私の注文",
  "myOrderImage": "画像",
  "productName": "商品名",
  "sku": "SKU",
  "price": "価格",
  "quantity": "数量",
  "status": "スターテス",
  "action": "アクション",
  "paymentMethod": " 支払方法",
  "shippingAddress": "お届け先の住所",
  "billingAddress": "請求先住所",
  "continueShopping": "ショッピングを続ける",
  "freuentlyAskedQueText": "よくある質問",
  "shopAndPlaceOrder": "買い物と注文の方法は？",
  "accountToPlaceOrderQues": "注文するにはアカウントが必要ですか？",
  "accountToPlaceOrderAns": "いいえ、必要なのはメールアドレスだけです。アカウントに登録してウィッシュリストにピースを追加することをお勧めしますが、ゲストとして注文して追跡し、自分に合った時間にサインアップすることもできます。",
  "registeredCustomersText": "登録済みの客",
  "registeredCustomersDescriptionText": "アカウントをお持ちの場合は、\nメールアドレスでログインしてください。",
  "usernameText": "ユーザー名",
  "passwordText": "パスワード",
  "signInText": "サインイン",
  "forgotYourPasswordText": "パスワードをお忘れですか？",
  "newCustomersText": "新しいお客様",
  "loginDescriptionText": "アカウントの作成には多くの利点があります。\nチェックアウトを高速化し、複数の住所を保持し、\n注文を追跡します。",
  "createAccountText": "アカウントを作成する",
  "firstNameText": "ファーストネーム",
  "lastNameText": "苗字",
  "dateOfBirthText": "生年月日",
  "pleaseSelectValidDateText": "有効な日付を選択してください",
  "marriageAnniversaryText": "結婚記念日",
  "emailText": "Eメール",
  "confirmPasswordText": "パスワードを認証する",
  "signUpForNewsletterText": "ニュースレターにサインアップ",
  "forgotYourPasswordDescriptionText": "パスワードリセットリンクを受信するには、以下にメールアドレスを入力してください\ n",
  "enterYourEmailText": "メールアドレスを入力",
  "resetMyPasswordText": "私のパスワードをリセットする",
  "accessYourAccountDetailsText": "アカウントの詳細と特典にアクセスする",
  "signUpText": "サインアップ",
  "myOrdersText": "私の注文",
  "myWishlistText": "私のウィッシュリスト",
  "addressBookText": "住所録",
  "accountInformationText": "口座情報",
  "myTicketsText": "私のチケット",
  "trackOrderText": "注文を追跡する",
  "companyMyAccountText": "会社",
  "contactUsText": "お問い合わせ",
  "secureShoppingText": "安全なショッピング",
  "advancedSearchText": "高度な検索",
  "testimonialsText": "お客様の声",
  "socialMyAccountText": "社交",
  "hopeText": "望む",
  "affiliateProgramText": "アフィリエイトプログラム",
  "influencerRegistrationText": "インフルエンサー登録",
  "exchangeText": "交換と返品",
  "contactMyAccountText": "連絡先",
  "privacyPolicyText": "プライバシーポリシー",
  "termsConditionsText": "利用規約",
  "shippingText": "運送",
  "aboutText": "だいたい",
  "aboutUsMyAccountText": "私たちに関しては",
  "referFriendMyAccountText": "友達を紹介する",
  "returnsText": "返品と返金",
  "faqMyAccountText": "よくある質問",
  "myAccountText": "マイアカウント",
  "filtersText": "フィルタ",
  "priceText": "価格",
  "colorText": "色",
  "brandText": "ブランド",
  "sizeText": "サイズ",
  "applyText": "申し込み",
  "searchText": "検索..",
  "aboutUsContain1": "SOLOは、世界中に1か月あたり500万人の訪問者がいるトップオンラインラグジュアリーファッションデスティネーションです。",
  "aboutUsContain2": 'このウェブサイトには、一流のデザイナーと若くて新しい才能の最高のセレクションが掲載されています。 Soloは、1930年代初頭にフィレンツェで設立され、Via Romaに同社の名を冠したコンセプトストアをオープンしました。1999年以来、同社は総収益の90％をオンライン販売に割り当てています。現在でも、創業者の孫であるAndrea PanconesiがCEOを務め、娘のAnnagreta Panconesiがクリエイティブディレクターを務める、100％個人経営の家族経営の会社です。',
  "aboutUsContain3": 'このサイトでは、バレンシアガ、ベテメンツ、オフホワイト、J.W。などの最も有名なデザイナーの男性、女性、子供向けの製品を取り揃え、衣料品、靴、バッグ、アクセサリー、高級住宅のインテリア、美容を幅広く取り揃えています。アンダーソン、バルマン、ドルチェ＆ガッバーナ、グッチ、サンローラン、バレンチノ、ジバンシィ、ロエベ、ジャックムスなど。',
  "aboutUsContain4": '現在、15か国から200人が、Soloの制作と保守に取り組んでいます。このサイトは、英語、イタリア語、ドイツ語、中国語、ロシア語、スペイン語、フランス語、韓国語、日本語の9か国語で利用できます。このサイトは完全に社内で作成されており、フィレンツェのオフィスにはグラフィックデザイン、IT、カスタマーサービス、マーケティング、購入の各部門があります。スタイリストとプレスチームは、世界のファッションの中心地であるミラノのソロオフィスで活動しています。',
  "aboutUsContain5": 'すべての注文は、Solo本社から、シグネチャーシューズバッグからパーソナライズされたリボンまで、細心の注意を払って準備され、最高の素材を使用したボックスで世界中に発送されます。',
  "aboutUsContain6": 'Soloは2008年に150万人のユニークビジターがサイトにアクセスし、2017年には5300万人のユニークビジターに成長しました。オンライン売上の15％以上が米国からのもので、ドイツ、英国、イタリア、中国、フランスがそれに続きます。',
  "aboutUsContain7": 'Soloは、Buy It First、Luxury Club、Sneakers Club、LVR Privilege、LVR Editionsなど、一連の独占的なサービスと商標イニシアチブにより、オンラインとオフラインの両方で高級小売業界の限界を押し広げています。',
  "profile": "プロフィール",
  "ContactNoText" : "連絡先番号。",
  "websiteUrlText" : "ウェブサイトのURL",
  "countryText" : "国",
  "postCodeText" : "郵便番号",
  "socialLinksText" : "「ソーシャルリンク",
  "facebookText" : "フェイスブック",
  "instagramText" : "インスタグラム",
  "twitterText" : "ツイッター",
  "youtubeText" : "「Youtube",
  "linkendinText" : "「リンケンディン",
  "pinterestText" : "「Pinterest",
  "followersText" : "「フォロワー",
  "workedOnText" : "「プロジェクトは",
  "mr": "氏。",
  "yourEmail1Text": "あなたのEメール",
  "subscribeText": "購読",
  "menuText": "メニュー",
  "accountText": "アカウント",
  "checkOutText": "チェックアウト",
  "purchaseText": "購入を完了するには、以下に詳細を入力してください",
  "shippingAddressText": "お届け先の住所",
  "shippingMethodText": "配送方法",
  "paymentMethodText": "支払方法",
  "orderSummaryText": "注文の概要",
  "alreadyAcText": "あなたはすでに私たちのアカウントを持っています。サインインするか、ゲストとして続行します。",
  "loginText": "ログインする",
  "forgotText": "パスワードをお忘れですか？",
  "stLineText": "番地：1号線",
  "cityText": "市",
  "japanText": "日本",
  "stateText": "州/県",
  "zipPostalText": "郵便番号/郵便番号",
  "phoneNumberText": "電話番号",
  "itemInCartText": "カート内のアイテム",
  "qtyText": "数量",
  "viewDetailsText": "詳細を見る",
  "applyDisCodeText": "割引コードを適用する",
  "enterDisCodeText": "割引コードを入力してください",
  "applyDiscountText": "割引を適用する",
  "orderTotalText": "注文合計",
  "placeOrderText": "注文する",
};
