const Map<String, String> ko = {
  "language": "영어",
  "appNameText": "솔로 럭셔리",
  "aboutUsText": "회사 소개",
  "referFriendText": "친구 추천",
  "returnsRefundsText": "반품 및 환불",
  "faqText": "자주하는 질문",
  "contactText": "연락하다",
  "socialText": "사회의",
  "companyText": "회사",
  "contactUs": "문의하기",
  "myOrders": "내 주문",
  "myOrderImage": "영상",
  "productName": "상품명",
  "sku": "SKU",
  "price": "가격",
  "quantity": "수량",
  "status": "상태",
  "action": "동작",
  "paymentMethod": " 지불 방법",
  "shippingAddress": "배송 주소",
  "billingAddress": "청구 지 주소",
  "continueShopping": "쇼핑을 계속",
  "freuentlyAskedQueText": "자주 묻는 질문",
  "shopAndPlaceOrder": "쇼핑 및 주문은 어떻게 하나요?",
  "accountToPlaceOrderQues": "주문하려면 계정이 필요합니까?",
  "accountToPlaceOrderAns": "아니요, 이메일 주소만 있으면 됩니다. 위시리스트에 제품을 추가하려면 계정에 등록하는 것이 좋지만, 원하는 시간에 게스트로 주문하고 등록할 수도 있습니다.",
  "registeredCustomersText": "등록된 고객",
  "registeredCustomersDescriptionText": "계정이 있으면\n이메일 주소로 로그인하십시오.",
  "usernameText": "사용자 이름",
  "passwordText": "비밀번호",
  "signInText": "로그인",
  "forgotYourPasswordText": "비밀번호를 잊어 버렸습니까?",
  "newCustomersText": "신규 고객",
  "loginDescriptionText": "계정을 만들면\n더 빠르게 체크아웃하고, 둘 이상의 주소를\n추적하는 등 많은 이점이 있습니다.",
  "createAccountText": "계정 만들기",
  "firstNameText": "이름",
  "lastNameText": "성",
  "dateOfBirthText": "생일",
  "pleaseSelectValidDateText": "유효한 날짜를 선택하세요",
  "marriageAnniversaryText": "결혼 기념일",
  "emailText": "이메일",
  "confirmPasswordText": "비밀번호 확인",
  "signUpForNewsletterText": "뉴스레터 신청",
  "forgotYourPasswordDescriptionText": "아래에 이메일 주소를 입력하여\n비밀번호 재설정 링크를 받으십시오",
  "enterYourEmailText": "이메일을 입력하세요",
  "resetMyPasswordText": "내 비밀번호 재설정",
  "accessYourAccountDetailsText": "계정 세부 정보 및 보상에 액세스",
  "signUpText": "가입하기",
  "myOrdersText": "내 주문",
  "myWishlistText": "내 위시리스트",
  "addressBookText": "주소록",
  "accountInformationText": "계정 정보",
  "myTicketsText": "내 티켓",
  "trackOrderText": "주문을 추적하다",
  "companyMyAccountText": "회사",
  "contactUsText": "문의하기",
  "secureShoppingText": "안전한 쇼핑",
  "advancedSearchText": "고급 검색",
  "testimonialsText": "사용후기",
  "socialMyAccountText": "사회의",
  "hopeText": "희망",
  "affiliateProgramText": "제휴 프로그램",
  "influencerRegistrationText": "인플루언서 등록",
  "exchangeText": "교환 및 반품",
  "contactMyAccountText": "콘택트 렌즈",
  "privacyPolicyText": "개인 정보 정책",
  "termsConditionsText": "이용약관",
  "shippingText": "배송",
  "aboutText": "에 대한",
  "aboutUsMyAccountText": "회사 소개",
  "referFriendMyAccountText": "친구 추천",
  "returnsText": "반품 및 환불",
  "faqMyAccountText": "자주하는 질문",
  "myAccountText": "내 계정",
  "filtersText": "필터",
  "priceText": "가격",
  "colorText": "색깔",
  "brandText": "상표",
  "sizeText": "크기",
  "applyText": "적용하다",
  "searchText": "검색..",
  "aboutUsContain1": "SOLO는 월 500만 방문자가 방문하는 최고의 온라인 럭셔리 패션 여행지입니다.",
  "aboutUsContain2": '이 웹 사이트는 최고의 기성 디자이너와 젊은 신진 재능을 엄선하여 제공합니다. Solo는 1930년대 초 피렌체에서 Via Roma.Online에 회사의 이름을 딴 컨셉 스토어를 열면서 설립되었습니다. 1999년 이후로 회사는 총 수익의 90%를 온라인 판매로 돌립니다. 오늘날까지 창업자의 손자 Andrea Panconesi가 CEO로, 그의 딸 Annagreta Panconesi가 크리에이티브 디렉터로 활동하는 100% 개인 소유 가족 기업으로 남아 있습니다.',
  "aboutUsContain3": '이 사이트는 Balenciaga, Vetements, Off-White, J.W. Anderson, Balmain, Dolce & Gabbana, Gucci, Saint Laurent, Valentino, Givenchy, Loewe, Jacquemus 등.',
  "aboutUsContain4": '현재 15개국에서 200명의 사람들이 Solo를 생산하고 유지하기 위해 일하고 있습니다. 이 사이트는 영어, 이탈리아어, 독일어, 중국어, 러시아어, 스페인어, 프랑스어, 한국어 및 일본어의 9개 언어로 제공됩니다. 이 사이트는 그래픽 디자인, IT, 고객 서비스, 마케팅 및 구매 부서가 있는 Florence 사무실과 함께 완전히 사내에서 만들어졌습니다. 스타일리스트와 프레스 팀은 세계 패션의 중심지인 밀라노의 솔로 오피스에서 활동합니다.',
  "aboutUsContain5": '모든 주문은 Solo 본사에서 시그니처 신발 가방에서 맞춤형 리본에 이르기까지 최고의 자재를 사용하여 최대한 주의를 기울여 준비된 상자에 담아 전 세계로 배송됩니다.',
  "aboutUsContain6": 'Solo는 2008년에 150만 명의 고유 방문자가 사이트에 액세스했으며 2017년에는 5,300만 명의 고유 방문자로 성장했습니다. 온라인 판매의 15% 이상이 미국에서 발생하고 독일, 영국, 이탈리아, 중국 및 프랑스가 그 뒤를 잇습니다.',
  "aboutUsContain7": 'Solo는 Buy It First, Luxury Club, Sneakers Club, LVR Privilege 및 LVR Editions를 포함한 일련의 독점 서비스 및 상표 이니셔티브를 통해 온라인과 오프라인 모두에서 럭셔리 소매 환경의 경계를 확장합니다.',
  "profile": "프로필",
  "ContactNoText" : "연락처.",
  "websiteUrlText" : "웹 사이트 주소",
  "countryText" : "국가",
  "postCodeText" : "우편번호",
  "socialLinksText" : "소셜 링크",
  "facebookText" : "페이스북",
  "instagramText" : "인스 타 그램",
  "twitterText" : "트위터",
  "youtubeText" : "유튜브",
  "linkendinText" : "린켄딘",
  "pinterestText" : "핀터레스트",
  "followersText" : "팔로워",
  "workedOnText" : "작업한 프로젝트",
  "mr": "씨.",
  "yourEmail1Text": "귀하의 이메일",
  "subscribeText": "구독하다",
  "menuText": "메뉴",
  "accountText": "계정",
  "checkOutText": "점검",
  "purchaseText": "구매를 완료하려면 아래에 세부 정보를 입력하십시오",
  "shippingAddressText": "배송 주소",
  "shippingMethodText": "배송 방법",
  "paymentMethodText": "지불 방법",
  "orderSummaryText": "주문 요약",
  "alreadyAcText": "이미 계정이 있습니다. 로그인하거나 게스트로 계속하십시오.",
  "loginText": "로그인",
  "forgotText": "비밀번호를 잊어 버렸습니까?",
  "stLineText": "주소: 1호선",
  "cityText": "도시",
  "japanText": "일본",
  "stateText": "시/도",
  "zipPostalText": "우편번호",
  "phoneNumberText": "전화 번호",
  "itemInCartText": "장바구니에 담긴 상품",
  "qtyText": "수량",
  "viewDetailsText": "세부 정보보기",
  "applyDisCodeText": "할인 코드 적용",
  "enterDisCodeText": "할인 코드 입력",
  "applyDiscountText": "할인 적용",
  "orderTotalText": "주문 합계",
  "placeOrderText": "주문하기",
};
