const Map<String, String> nl = {
  "language": "Engels",
  "appNameText": "Individuele luxe",
  "aboutUsText": "Over ons",
  "referFriendText": "Verwijs vriend",
  "returnsRefundsText": "Retourneren & Terugbetalingen",
  "faqText": "FAQ",
  "contactText": "Contact",
  "socialText": "sociaal",
  "companyText": "Bedrijf",
  "contactUs": "Neem contact op",
  "myOrders": "mijn bestellingen",
  "myOrderImage": "Afbeelding",
  "productName": "productnaam",
  "sku": "Artikelnummer",
  "price": "Prijs",
  "quantity": "aantal",
  "status": "Toestand",
  "action": "Actie",
  "paymentMethod": " Betalingswijze",
  "shippingAddress": "Verzendingsadres",
  "billingAddress": "factuur adres",
  "continueShopping": "Doorgaan met winkelen",
  "freuentlyAskedQueText": "Veel Gestelde Vragen",
  "shopAndPlaceOrder": "Hoe winkelen & een bestelling plaatsen?",
  "accountToPlaceOrderQues": "Heb ik een account nodig om een ​​bestelling te plaatsen?",
  "accountToPlaceOrderAns": "Nee, je hebt alleen een e-mailadres nodig. We raden je aan om je te registreren voor een account om stukken aan je verlanglijstje toe te voegen, maar je kunt ook als gast bestellingen plaatsen en volgen en je aanmelden op een tijdstip dat jou uitkomt.",
  "registeredCustomersText": "geregistreerde klanten",
  "registeredCustomersDescriptionText": "Als u een account heeft, logt u in met uw\ne-mailadres.",
  "usernameText": "gebruikersnaam",
  "passwordText": "Wachtwoord",
  "signInText": "Aanmelden",
  "forgotYourPasswordText": "Uw wachtwoord vergeten?",
  "newCustomersText": "nieuwe klanten",
  "loginDescriptionText": "Het aanmaken van een account heeft veel voordelen: check\nout sneller, bewaar meer dan één adres\nvolg bestellingen en meer.",
  "createAccountText": "Maak account",
  "firstNameText": "Voornaam",
  "lastNameText": "Achternaam",
  "dateOfBirthText": "Geboortedatum",
  "pleaseSelectValidDateText": "Selecteer een geldige datum",
  "marriageAnniversaryText": "Trouwdag",
  "emailText": "E-mail",
  "confirmPasswordText": "bevestig wachtwoord",
  "signUpForNewsletterText": "Aanmelden voor Nieuwsbrief",
  "forgotYourPasswordDescriptionText": "Voer hieronder uw e-mailadres in om een ​​\nEen wachtwoordherstellink te ontvangen",
  "enterYourEmailText": "Vul je e-mailadres in",
  "resetMyPasswordText": "Reset mijn wachtwoord",
  "accessYourAccountDetailsText": "Toegang tot uw accountgegevens en beloningen",
  "signUpText": "AANMELDEN",
  "myOrdersText": "mijn bestellingen",
  "myWishlistText": "Mijn wenslijst",
  "addressBookText": "Adresboek",
  "accountInformationText": "Account Informatie",
  "myTicketsText": "Mijn Tickets",
  "trackOrderText": "Order volgen",
  "companyMyAccountText": "Bedrijf",
  "contactUsText": "Neem contact op",
  "secureShoppingText": "Veilig winkelen",
  "advancedSearchText": "geavanceerd zoeken",
  "testimonialsText": "Getuigenissen",
  "socialMyAccountText": "sociaal",
  "hopeText": "Hoop",
  "affiliateProgramText": "Affiliate-programma",
  "influencerRegistrationText": "Influencer-registratie",
  "exchangeText": "Ruilen en retourneren",
  "contactMyAccountText": "Contacten",
  "privacyPolicyText": "Privacybeleid",
  "termsConditionsText": "algemene voorwaarden",
  "shippingText": "Verzending",
  "aboutText": "Over",
  "aboutUsMyAccountText": "Over ons",
  "referFriendMyAccountText": "Verwijs vriend",
  "returnsText": "Retourneren & Terugbetalingen",
  "faqMyAccountText": "FAQ",
  "myAccountText": "Mijn rekening",
  "filtersText": "Filters",
  "priceText": "Prijs",
  "colorText": "Kleur",
  "brandText": "Merk",
  "sizeText": "Maat",
  "applyText": "Van toepassing zijn",
  "searchText": "Zoekopdracht..",
  "aboutUsContain1": "SOLO IS EEN TOP ONLINE LUXEFASHION BESTEMMING MET 5 MILJOEN BEZOEKERS PER MAAND WERELDWIJD VERZENDING.",
  "aboutUsContain2": "De website biedt de beste selectie van de beste gevestigde ontwerpers en jonge opkomende talenten. Solo werd begin jaren dertig opgericht in Florence, met de opening van de gelijknamige conceptstore van het bedrijf aan de Via Roma. Online sinds 1999 schrijft het bedrijf 90% van de totale omzet toe aan onlineverkopen. Tot op de dag van vandaag blijft het een 100% particulier familiebedrijf, met de kleinzoon van de oprichter, Andrea Panconesi, als CEO en zijn dochter, Annagreta Panconesi als creatief directeur.",
  "aboutUsContain3": "De site biedt een brede selectie van kleding, schoenen, tassen, accessoires, luxe interieurs en schoonheid, met producten voor mannen, vrouwen en kinderen van de meest prestigieuze ontwerpers zoals Balenciaga, Vetements, Off-White, J.W. Anderson, Balmain, Dolce & Gabbana, Gucci, Saint Laurent, Valentino, Givenchy, Loewe, Jacquemus en meer.",
  "aboutUsContain4": 'Er zijn momenteel 200 mensen uit 15 verschillende landen die werken aan de productie en het onderhoud van Solo. De site is beschikbaar in 9 talen: Engels, Italiaans, Duits, Chinees, Russisch, Spaans, Frans, Koreaans en Japans. De site is volledig in eigen beheer gemaakt, met de afdelingen grafisch ontwerp, IT, klantenservice, marketing en inkoop in Florence. De stylisten en persteams opereren vanuit het Solo-kantoor in de modehoofdstad van de wereld - Milaan.',
  "aboutUsContain5": 'Alle bestellingen worden wereldwijd verzonden vanuit het Solo-hoofdkantoor in dozen die met maximale zorg zijn voorbereid en de beste materialen gebruiken, van de kenmerkende schoenentassen tot het gepersonaliseerde lint.',
  "aboutUsContain6": 'Solo had in 2008 1,5 miljoen unieke bezoekers op de site en is in 2017 gegroeid tot 53 miljoen unieke bezoekers. Meer dan 15% van de online verkopen wordt gegenereerd in de Verenigde Staten, gevolgd door Duitsland, het VK, Italië, China en Frankrijk.',
  "aboutUsContain7": 'Solo verlegt de grenzen van het luxe retaillandschap, zowel online als offline met een scala aan exclusieve diensten en handelsmerkinitiatieven, waaronder Buy It First, Luxury Club, Sneakers Club, LVR Privilege en LVR Editions.',
  "profile": "Profiel",
  "ContactNoText" : "Contactnr.",
  "websiteUrlText" : "Website URL",
  "countryText" : "Land",
  "postCodeText" : "Postcode",
  "socialLinksText" : "Sociale links",
  "facebookText" : "Facebook",
  "instagramText" : "Instagram",
  "twitterText" : "Twitter",
  "youtubeText" : "Youtube",
  "linkendinText" : "Linkendin",
  "pinterestText" : "Pinterest",
  "followersText" : "Volgers",
  "workedOnText" : "Projecten waaraan gewerkt is",
  "mr" : "Dhr.",
  "yourEmail1Text": "Jouw email",
  "subscribeText": "ABONNEREN",
  "menuText": "Menu",
  "accountText": "Rekening",
  "checkOutText": "Uitchecken",
  "purchaseText": "Voer hieronder uw gegevens in om uw aankoop te voltooien:",
  "shippingAddressText": "Verzendingsadres",
  "shippingMethodText": "Verzendmethode:",
  "paymentMethodText": "Betalingswijze",
  "orderSummaryText": "overzicht van de bestelling",
  "alreadyAcText": "U heeft al een account bij ons. Log in of ga verder als gast.",
  "loginText": "LOG IN",
  "forgotText": "Uw wachtwoord vergeten?",
  "stLineText": "Straat Adres: Lijn 1",
  "cityText": "Stad",
  "japanText": "Japan",
  "stateText": "Staat/Provincie",
  "zipPostalText": "Postcode/postcode",
  "phoneNumberText": "Telefoonnummer",
  "itemInCartText": "Artikel in winkelwagen",
  "qtyText": "aantal",
  "viewDetailsText": "Details bekijken",
  "applyDisCodeText": "Kortingscode toepassen",
  "enterDisCodeText": "Voer kortingscode in",
  "applyDiscountText": "Korting toepassen",
  "orderTotalText": "totale bestelling",
  "placeOrderText": "PLAATS BESTELLING",
};
