const Map<String, String> ur = {
  "language": "انگریزی",
  "appNameText": "سولو لگژری",
  "aboutUsText": "ہمارے بارے میں",
  "referFriendText": "دوست سے رجوع کریں۔",
  "returnsRefundsText": "ریٹرن اور ریفنڈز",
  "faqText": "عمومی سوالات",
  "contactText": "رابطہ کریں۔",
  "socialText": "سماجی",
  "companyText": "کمپنی",
  "contactUs": "ہم سے رابطہ کریں۔",
  "myOrders": "میرے احکام",
  "myOrderImage": "تصویر",
  "productName": "پروڈکٹ کا نام",
  "sku": "SKU",
  "price": "قیمت",
  "quantity": "مقدار",
  "status": "حالت",
  "action": "عمل",
  "paymentMethod": " ادائیگی کا طریقہ",
  "shippingAddress": "شپنگ ایڈریس",
  "billingAddress": "بل کا پتہ",
  "continueShopping": "خریداری جاری",
  "freuentlyAskedQueText": "اکثر پوچھے گئے سوالات",
  "shopAndPlaceOrder": "خریداری اور آرڈر کیسے کریں؟",
  "accountToPlaceOrderQues": "کیا مجھے آرڈر دینے کے لیے اکاؤنٹ کی ضرورت ہے؟",
  "accountToPlaceOrderAns": "نہیں، آپ کو صرف ایک ای میل ایڈریس کی ضرورت ہے۔ ہم تجویز کرتے ہیں کہ آپ اپنی خواہش کی فہرست میں ٹکڑوں کو شامل کرنا شروع کرنے کے لیے ایک اکاؤنٹ کے لیے رجسٹر کریں، لیکن، آپ مہمان کے طور پر آرڈر بھی دے سکتے ہیں اور ٹریک بھی کر سکتے ہیں اور اس وقت سائن اپ کر سکتے ہیں جو آپ کے لیے مناسب ہو۔",
  "registeredCustomersText": "رجسٹرڈ صارفین",
  "registeredCustomersDescriptionText": "اگر آپ کا اکاؤنٹ ہے، تو اپنے\nای میل ایڈریس کے ساتھ سائن ان کریں۔",
  "usernameText": "صارف نام",
  "passwordText": "پاس ورڈ",
  "signInText": "سائن ان",
  "forgotYourPasswordText": "اپنا پاس ورڈ بھول گئے؟",
  "newCustomersText": "نئے گاہک",
  "loginDescriptionText": "اکاؤنٹ بنانے کے بہت سے فوائد ہیں: تیزی سے چیک آؤٹ کریں، ایک سے زیادہ پتے رکھیں\nآرڈرز کو ٹریک کریں اور مزید۔",
  "createAccountText": "اکاؤنٹ بنائیں",
  "firstNameText": "پہلا نام",
  "lastNameText": "آخری نام",
  "dateOfBirthText": "پیدائش کی تاریخ",
  "pleaseSelectValidDateText": "براہ کرم درست تاریخ منتخب کریں۔",
  "marriageAnniversaryText": "شادی کی سالگرہ",
  "emailText": "ای میل",
  "confirmPasswordText": "پاس ورڈ کی تصدیق کریں۔",
  "signUpForNewsletterText": "نیوز لیٹر کے لیے سائن اپ کریں۔",
  "forgotYourPasswordDescriptionText": "براہ کرم حاصل کرنے کے لیے نیچے اپنا ای میل ایڈریس درج کریں\nپاس ورڈ دوبارہ ترتیب دینے کا لنک",
  "enterYourEmailText": "اپنا ای میل درج کریں۔",
  "resetMyPasswordText": "میرا پاس ورڈ ری سیٹ کریں۔",
  "accessYourAccountDetailsText": "اپنے اکاؤنٹ کی تفصیلات اور انعامات تک رسائی حاصل کریں۔",
  "signUpText": "سائن اپ",
  "myOrdersText": "میرے احکام",
  "myWishlistText": "میری خواہشات کی فہرست",
  "addressBookText": "ایڈریس بک",
  "accountInformationText": "اکاؤنٹ کی معلومات",
  "myTicketsText": "میرے ٹکٹ",
  "trackOrderText": "اپنے آرڈر کا پتا لگائیے",
  "companyMyAccountText": "کمپنی",
  "contactUsText": "ہم سے رابطہ کریں۔",
  "secureShoppingText": "محفوظ خریداری",
  "advancedSearchText": "اعلی درجے کی تلاش",
  "testimonialsText": "تعریفیں",
  "socialMyAccountText": "سماجی",
  "hopeText": "امید",
  "affiliateProgramText": "ملحق پروگرام",
  "influencerRegistrationText": "متاثر کن رجسٹریشن",
  "exchangeText": "تبادلہ اور واپسی۔",
  "contactMyAccountText": "رابطے",
  "privacyPolicyText": "رازداری کی پالیسی",
  "termsConditionsText": "شرائط و ضوابط",
  "shippingText": "شپنگ",
  "aboutText": "کے بارے میں",
  "aboutUsMyAccountText": "ہمارے بارے میں",
  "referFriendMyAccountText": "دوست سے رجوع کریں۔",
  "returnsText": "ریٹرن اور ریفنڈز",
  "faqMyAccountText": "عمومی سوالات",
  "myAccountText": "میرا اکاونٹ",
  "filtersText": "فلٹرز",
  "priceText": "قیمت",
  "colorText": "رنگ",
  "brandText": "برانڈ",
  "sizeText": "سائز",
  "applyText": "درخواست دیں",
  "searchText": "تلاش کریں..",
  "aboutUsContain1": "سولو ایک اعلیٰ آن لائن لگژری فیشن کی منزل ہے جہاں ہر ماہ 5 ملین زائرین دنیا بھر میں شپنگ کرتے ہیں۔",
  "aboutUsContain2": 'اس ویب سائٹ میں اعلیٰ درجے کے ڈیزائنرز کے ساتھ ساتھ نوجوان ابھرتی ہوئی صلاحیتوں کا بہترین انتخاب بھی شامل ہے۔ سولو کی بنیاد فلورنس میں 1930 کی دہائی کے اوائل میں رکھی گئی تھی، جس میں 1999 سے Via Roma.Online پر کمپنی کے نامی تصوراتی اسٹور کے آغاز کے بعد، کمپنی کل آمدنی کا 90% آن لائن فروخت سے منسوب کرتی ہے۔ آج تک یہ 100% نجی ملکیت کا خاندانی کاروبار ہے، جس میں بانی کا پوتا، اینڈریا پینکونی سی ای او اور ان کی بیٹی، اناگریٹا پینکونسی بطور تخلیقی ڈائریکٹر کام کر رہی ہیں۔',
  "aboutUsContain3": 'یہ سائٹ کپڑوں، جوتوں، بیگز، لوازمات، لگژری ہوم انٹیریئرز اور خوبصورتی کا ایک وسیع انتخاب پیش کرتی ہے، جس میں مردوں، عورتوں اور بچوں کے لیے انتہائی نامور ڈیزائنرز جیسے Balenciaga، Vetements، Off-White، J.W. کی مصنوعات دستیاب ہیں۔ اینڈرسن، بالمین، ڈولس اور گبانا، گوچی، سینٹ لارینٹ، ویلنٹینو، گیوینچی، لوئی، جیکیمس اور بہت کچھ۔',
  "aboutUsContain4": 'اس وقت 15 مختلف ممالک کے 200 لوگ ہیں جو سولو کی تیاری اور دیکھ بھال کے لیے کام کرتے ہیں۔ یہ سائٹ 9 زبانوں میں دستیاب ہے: انگریزی، اطالوی، جرمن، چینی، روسی، ہسپانوی، فرانسیسی، کورین اور جاپانی۔ یہ سائٹ مکمل طور پر اندرون خانہ بنائی گئی ہے، جس میں فلورنس آفس ہاؤسنگ گرافک ڈیزائن، آئی ٹی، کسٹمر سروس، مارکیٹنگ اور خریداری کے شعبے شامل ہیں۔ اسٹائلسٹ اور پریس ٹیمیں دنیا کے فیشن کے دارالحکومت میلان میں سولو آفس سے کام کرتی ہیں۔',
  "aboutUsContain5": 'تمام آرڈرز سولو ہیڈ کوارٹر سے باکسز میں بھیجے جاتے ہیں جو زیادہ سے زیادہ احتیاط کے ساتھ تیار کیے جاتے ہیں اور بہترین مواد استعمال کرتے ہیں، دستخط والے جوتے کے تھیلے سے لے کر ذاتی نوعیت کے ربن تک۔',
  "aboutUsContain6": 'سولو نے 2008 میں سائٹ تک 1.5 ملین منفرد وزیٹرس تک رسائی حاصل کی تھی اور 2017 میں 53 ملین منفرد وزیٹرس تک پہنچ گئے ہیں۔ آن لائن سیلز کا 15% سے زیادہ امریکہ سے پیدا ہوتا ہے، اس کے بعد جرمنی، برطانیہ، اٹلی، چین اور فرانس کا نمبر آتا ہے۔',
  "aboutUsContain7": 'سولو خصوصی خدمات اور ٹریڈ مارک اقدامات کی ایک صف کے ساتھ آن اور آف لائن لگژری ریٹیل لینڈ سکیپ کی حدود کو آگے بڑھاتا ہے جس میں Buy It First, Luxury Club, Sneakers Club, LVR Privilege اور LVR Editions شامل ہیں۔',
  "profile": "پروفائل",
  "ContactNoText" : "رابطے کا نمبر.",
  "websiteUrlText" : "ویب سائٹ کا پتا",
  "countryText" : "ملک",
  "postCodeText" : "پوسٹ کوڈ",
  "socialLinksText" : "سماجی روابط",
  "facebookText" : "فیس بک",
  "instagramText" : "انسٹاگرام",
  "twitterText" : "ٹویٹر",
  "youtubeText" : "یوٹیوب",
  "linkendinText" : "لنکنڈن",
  "pinterestText" : "Pinterest",
  "followersText" : "پیروکار",
  "workedOnText" : "منصوبوں پر کام ہوا۔",
  "mr": "مسٹر.",
  "yourEmail1Text": "آپ کا ای میل",
  "subscribeText": "سبسکرائب",
  "menuText": "مینو",
  "accountText": "کھاتہ",
  "checkOutText": "اس کو دیکھو",
  "purchaseText": "اپنی خریداری مکمل کرنے کے لیے براہ کرم نیچے اپنی تفصیلات درج کریں۔",
  "shippingAddressText": "شپنگ ایڈریس",
  "shippingMethodText": "بھیجنے کا طریقہ",
  "paymentMethodText": "ادائیگی کا طریقہ",
  "orderSummaryText": "حکم کا خلاصہ",
  "alreadyAcText": "آپ کا پہلے سے ہی ہمارے ساتھ اکاؤنٹ ہے۔ سائن ان کریں یا بطور مہمان جاری رکھیں۔",
  "loginText": "لاگ ان کریں",
  "forgotText": "اپنا پاس ورڈ بھول گئے؟",
  "stLineText": "گلی کا پتہ: لائن 1",
  "cityText": "شہر",
  "japanText": "جاپان",
  "stateText": "ریاست/صوبہ",
  "zipPostalText": "زپ / پوسٹل کوڈ",
  "phoneNumberText": "فون نمبر",
  "itemInCartText": "ٹوکری میں آئٹم",
  "qtyText": "مقدار",
  "viewDetailsText": "تفصیلات دیکھیں",
  "applyDisCodeText": "ڈسکاؤنٹ کوڈ کا اطلاق کریں۔",
  "enterDisCodeText": "ڈسکاؤنٹ کوڈ درج کریں۔",
  "applyDiscountText": "ڈسکاؤنٹ کا اطلاق کریں۔",
  "orderTotalText": "ٹوٹل آرڈر",
  "placeOrderText": "حکم صادر کریں",
  "storePaymentText": "ذخیرہ شدہ ادائیگی کے طریقے",
  "newsLetterText": "نیوز لیٹر سبسکرپشنز",
};
